CampusDual/cd2024bfs4g1

cd2024bfs4g1-api/src/main/java/com/campusdual/cd2024bfs4g1/api/core/service/IStudentBootcampService.java, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/bootcamps/bootcamp-details/bootcamp-details.component.html, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/bootcamps/bootcamp-details/bootcamp-details.component.ts, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/bootcamps/bootcamp-details/student-bootcamp-add/student-bootcamp-add.component.html, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/bootcamps/bootcamp-details/student-bootcamp-add/student-bootcamp-add.component.spec.ts, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/bootcamps/bootcamp-details/student-bootcamp-add/student-bootcamp-add.component.ts, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/bootcamps/bootcamp-list/bootcamp-list.component.html, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/bootcamps/bootcamp-list/bootcamp-list.component.ts, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/bootcamps/bootcamps-routing.module.ts, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/bootcamps/bootcamps.module.ts, cd2024bfs4g1-frontend/src/main/ngx/src/app/shared/app.services.config.ts, cd2024bfs4g1-model/src/main/java/com/campusdual/cd2024bfs4g1/model/core/dao/StudentBootcampDao.java, cd2024bfs4g1-model/src/main/java/com/campusdual/cd2024bfs4g1/model/core/service/StudentBootcampDao.java, cd2024bfs4g1-model/src/main/java/com/campusdual/cd2024bfs4g1/model/core/service/StudentBootcampService.java, cd2024bfs4g1-model/src/main/resources/dao/StudentBootcampDao.xml
Tarea terminada lista para test
=> BFS42024-19

cd2024bfs4g1-frontend/src/main/ngx/src/app/main/bootcamps/bootcamp-list/bootcamp-list.component.html, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/bootcamps/bootcamp-new/bootcamp-new.component.html, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/students/students-detail/students-detail.component.html, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/students/students-new/students-new.component.html, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/students/students-table/students-table.component.html, cd2024bfs4g1-frontend/src/main/ngx/src/assets/i18n/en.json, cd2024bfs4g1-frontend/src/main/ngx/src/assets/i18n/es.json
=> bug-fix-all

cd2024bfs4g1-frontend/src/main/ngx/src/app/main/students/students-table/students-table.component.css, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/students/students-table/students-table.component.html
Fix de las scroll de la pestaña alumno
=> bug-fix-79

cd2024bfs4g1-frontend/src/main/ngx/src/app/main/home/home.component.html, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/home/home.component.scss, cd2024bfs4g1-frontend/src/main/ngx/src/assets/i18n/en.json, cd2024bfs4g1-frontend/src/main/ngx/src/assets/i18n/es.json
Actualización de estilo y traducción de calendario
=> bug-fix-87

cd2024bfs4g1-frontend/src/main/ngx/src/app/main/students/students-detail/students-detail.component.html, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/students/students-new/students-new.component.html
=> Birth date y campo udemy bug fix

cd2024bfs4g1-frontend/src/main/ngx/src/app/main/bootcamps/bootcamp-list/bootcamp-list.component.html, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/students/students-table/students-table.component.html, cd2024bfs4g1-frontend/src/main/ngx/src/assets/i18n/en.json, cd2024bfs4g1-frontend/src/main/ngx/src/assets/i18n/es.json
Dar un titulo a las listas de estudiantes y bootcamps
=> Dar un titulo a las listas de estudiantes y bootcamps

cd2024bfs4g1-frontend/src/main/ngx/src/app/main/bootcamps/bootcamp-details/bootcamp-details.component.css, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/bootcamps/bootcamp-details/bootcamp-details.component.html, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/bootcamps/bootcamp-list/bootcamp-list.component.css, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/bootcamps/bootcamp-list/bootcamp-list.component.html, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/main.component.html, cd2024bfs4g1-frontend/src/main/ngx/src/styles.scss
Estilo de detalle de bootcamp terminado 100% real no fake
=> BFS42024-24

cd2024bfs4g1-frontend/src/main/ngx/src/app/main/students/students-detail/students-detail.component.html, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/students/students-detail/students-detail.component.ts, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/students/students-new/students-new.component.css, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/students/students-new/students-new.component.html, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/students/students-new/students-new.component.ts
Uso de UpperCamelCase para añadir y editar alumnos en campos seleccionados
=> bug-fix-104

cd2024bfs4g1-frontend/src/main/ngx/src/app/main/students/students-detail/students-detail.component.html
DNI solucionado en pestaña de student detail
=> Arreglo DNI

cd2024bfs4g1-frontend/src/main/ngx/src/app/main/bootcamps/bootcamp-details/bootcamp-details.component.html, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/students/students-detail/students-detail.component.html, cd2024bfs4g1-frontend/src/main/ngx/src/styles.scss
añadidos checkbox a las tablas de detalle de bootcamp y alumnos
=> añadidos los checkbox a las tablas de detalle de students y bootcamp

cd2024bfs4g1-frontend/src/main/ngx/src/app/login/login.component.ts, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/data/personal-info/personal-info.component.css, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/data/personal-info/personal-info.component.html, cd2024bfs4g1-model/src/main/java/com/campusdual/cd2024bfs4g1/model/core/service/UserAndRoleService.java
Actualizado del routing en login para poder entrar sin que salte el mensaje de permisos. Arreglado de css para que no aparezca scrollbar
=> BFS42024-30

cd2024bfs4g1-api/src/main/java/com/campusdual/cd2024bfs4g1/api/core/service/IStudentStatusService.java, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/bootcamps/bootcamps-routing.module.ts, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/config/config-routing.module.ts, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/config/config-tables/config-tables.component.html, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/config/config-tables/config-tables.component.ts, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/config/config.module.ts, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/config/employment-status-details/employment-status-details.component.html, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/config/employment-status-new/employment-status-new.component.html, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/config/student-status-details/student-status-details.component.html, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/config/student-status-details/student-status-details.component.ts, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/config/student-status-new/student-status-new.component.html, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/config/student-status-new/student-status-new.component.ts, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/students/students-detail/bootcamp-student-add/bootcamp-student-add.component.html, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/students/students-detail/students-detail.component.html, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/students/students-new/students-new.component.html, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/students/students-table/students-table.component.html, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/students/students-table/students-table.component.ts, cd2024bfs4g1-frontend/src/main/ngx/src/app/shared/app.services.config.ts, cd2024bfs4g1-frontend/src/main/ngx/src/assets/i18n/en.json, cd2024bfs4g1-frontend/src/main/ngx/src/assets/i18n/es.json, cd2024bfs4g1-frontend/src/main/ngx/src/styles.scss, cd2024bfs4g1-model/src/main/java/com/campusdual/cd2024bfs4g1/model/core/dao/StudentDao.java, cd2024bfs4g1-model/src/main/java/com/campusdual/cd2024bfs4g1/model/core/dao/StudentStatusDao.java, cd2024bfs4g1-model/src/main/java/com/campusdual/cd2024bfs4g1/model/core/service/EmploymentStatusService.java, cd2024bfs4g1-model/src/main/java/com/campusdual/cd2024bfs4g1/model/core/service/StudentStatusService.java, cd2024bfs4g1-model/src/main/resources/dao/StudentDao.xml, cd2024bfs4g1-model/src/main/resources/dao/StudentStatusDao.xml, cd2024bfs4g1-model/src/main/resources/db/migration/V13__create_table_student_status.sql, cd2024bfs4g1-ws/src/main/java/com/campusdual/cd2024bfs4g1/ws/core/rest/StudentStatusController.java
Agregamos a CONFIG otra tabla para el employment status y lo que modifiques en ella afecta a los employment status de alumnos y al filtrado
=> BFS42024-132

cd2024bfs4g1-frontend/src/main/ngx/src/app/main/bootcamps/bootcamp-details/bootcamp-details.component.html, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/config/config-tables/config-tables.component.css, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/config/config-tables/config-tables.component.html, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/students/students-detail/students-detail.component.html, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/students/students-new/students-new.component.html, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/students/students-table/students-table.component.html, cd2024bfs4g1-frontend/src/main/ngx/src/assets/i18n/es.json, cd2024bfs4g1-frontend/src/main/ngx/src/styles.scss
Corrección doble * en label estado & Modificar tablas config para colacarlas una al lado de la otra y que se cambie a una debajo de otra al reducir la ventana.
=> BFS42024-132-BugFix

cd2024bfs4g1-frontend/src/main/ngx/src/app/main/students/students-table/students-table.component.css, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/students/students-table/students-table.component.html, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/students/students-table/students-table.component.ts, cd2024bfs4g1-frontend/src/main/ngx/src/app/shared/app.services.config.ts, cd2024bfs4g1-frontend/src/main/ngx/src/assets/i18n/en.json, cd2024bfs4g1-frontend/src/main/ngx/src/assets/i18n/es.json, cd2024bfs4g1-frontend/src/main/ngx/src/styles.scss
Ediciones en ficheros de traduccion y students table html y css
=> Arreglado bug en filtrado de estudiantes (grupo E)

cd2024bfs4g1-frontend/src/main/ngx/src/app/main/students/students-detail/students-detail.component.html, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/students/students-new/students-new.component.html, cd2024bfs4g1-model/src/main/resources/dao/StudentDao.xml, cd2024bfs4g1-model/src/main/resources/db/migration/V26__table_student_to_fields_nullable.sql
Se añade V26, se cambia el studentsDAO.xml, se actualiza el front para quitar etiquetas de required en students.
=> BFS42024-197

cd2024bfs4g1-frontend/src/main/ngx/src/app/main/students/students-new/students-new.component.css, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/students/students-new/students-new.component.html
estilo nuevo estudiante( no lo queremos de vuelta )
=> BFS42024-144v4

cd2024bfs4g1-frontend/src/main/ngx/src/app/main/students/students-detail/students-detail.component.html, cd2024bfs4g1-frontend/src/main/ngx/src/assets/i18n/en.json, cd2024bfs4g1-frontend/src/main/ngx/src/assets/i18n/es.json
Se ha modificado la etiqueta documentos en student details
=> La label de Documentos en student details ahora es Documentos y bootcamps

cd2024bfs4g1-frontend/src/main/ngx/src/app/main/students/students-detail/students-detail.component.css, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/students/students-detail/students-detail.component.html, cd2024bfs4g1-frontend/src/main/ngx/src/assets/i18n/en.json, cd2024bfs4g1-frontend/src/main/ngx/src/assets/i18n/es.json
Cambiado Media Pantalla Datos Principales
Cambiado GitHub a Accesos
bug solucionado
Version updated
Files changed:
M	charts/cd2024bfs4g1/values-dev.yaml
Bfs42024 281 (#194)
* bug solucionado
* Añadidos textos a los errores
---------
=> Cambiado traductor

cd2024bfs4g1-frontend/src/main/ngx/src/app/main/commercial/commercial-section/commercial-section.component.html, cd2024bfs4g1-model/src/main/resources/dao/StudentDao.xml, cd2024bfs4g1-model/src/main/resources/db/migration/V43__delete_employment_status_id.sql
=> BFS32024-191-v4

cd2024bfs4g1-frontend/src/main/ngx/src/app/main/students/students-detail/students-detail.component.css, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/students/students-detail/students-detail.component.html, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/students/students-detail/students-detail.component.ts, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/students/students-new/students-new.component.css, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/students/students-new/students-new.component.html
Cambiar aviso dni para que no modifique el tamaño de los input
=> BFS42024-333

cd2024bfs4g1-frontend/src/main/ngx/src/app/main/students/students-detail/students-detail.component.ts
Fix: Seccion comercial vuelve a redirigir a las notas del alumno
=> BFS42024-346

cd2024bfs4g1-api/src/main/java/com/campusdual/cd2024bfs4g1/api/core/service/IUserAndRoleService.java, cd2024bfs4g1-model/src/main/java/com/campusdual/cd2024bfs4g1/model/core/service/StudentService.java, cd2024bfs4g1-model/src/main/java/com/campusdual/cd2024bfs4g1/model/core/service/UserAndRoleService.java, cd2024bfs4g1-model/src/main/resources/db/migration/V50__add_permission_usr_role_server_permission.sql
Fix: Ahora se eliminan los usuarios al eliminar un estudiante. (BFS42024-344-v2)
=> BFS42024-344

cd2024bfs4g1-api/src/main/java/com/campusdual/cd2024bfs4g1/api/core/service/IAttendanceService.java, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/bootcamps/bootcamp-details/bootcamp-details.component.html, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/bootcamps/bootcamp-details/bootcamp-details.component.ts, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/students/students-detail/students-detail.component.css, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/students/students-detail/students-detail.component.html, cd2024bfs4g1-frontend/src/main/ngx/src/app/main/students/students-detail/students-detail.component.ts, cd2024bfs4g1-frontend/src/main/ngx/src/assets/i18n/en.json, cd2024bfs4g1-frontend/src/main/ngx/src/assets/i18n/es.json, cd2024bfs4g1-model/src/main/java/com/campusdual/cd2024bfs4g1/model/core/service/AttendanceService.java, cd2024bfs4g1-model/src/main/java/com/campusdual/cd2024bfs4g1/model/core/service/StudentBootcampService.java
Fix: Ahora se eliminan los estudiantes con asistencias de la tabla StudentBootcamp & Button Delete con aviso de eliminación de asistencias
=> BFS42024-343
